#include "tkbc-uuid.h"

#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <time.h>

#include <fcntl.h>
#include <unistd.h>


/**
 * @brief The function returns the nil uuid. The nil uuid is the uuid where all
 * bytes are zero. It is used to represent the state where no script is loaded.
 *
 * @return The nil uuid.
 */
UUID tkbc_uuid_nil(void) {
    UUID uuid = {0};
    return uuid;
}

/**
 * @brief The function checks if the given uuid is the nil uuid.
 *
 * @param uuid The uuid that should be checked.
 * @return True if all bytes of the uuid are zero, otherwise false.
 */
bool tkbc_uuid_is_nil(UUID uuid) {
    UUID nil = tkbc_uuid_nil();
    return tkbc_uuid_equals(uuid, nil);
}

/**
 * @brief The function checks if the two given uuids are equal.
 *
 * @param a The first uuid that should be compared.
 * @param b The second uuid that should be compared.
 * @return True if the two uuids are byte wise equal, otherwise false.
 */
bool tkbc_uuid_equals(UUID a, UUID b) {
    return memcmp(a.bytes, b.bytes, sizeof(a.bytes)) == 0;
}


/**
 * @brief The function fills the given count of random bytes that are generated
 * from a random number generator that is provided by the operating system.
 *
 * @param buffer The buffer where the random bytes should be stored in.
 * @param count The amount of random bytes that should be generated.
 * @return True if the buffer could be filled with random data, otherwise false.
 */
static bool tkbc_uuid_fill_random_bytes(unsigned char *buffer, size_t count) {
    static uint64_t state = 0;
    if (state == 0) {
        state = ((uint64_t) time(NULL) ^ ((uint64_t) clock() << 32) ^ ((uint64_t) (size_t) buffer) ^
                 UINT64_C(0x9E3779B97F4A7C15));
    }
    for (size_t i = 0; i < count; ++i) {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        buffer[i] = (unsigned char) (state & 0xFF);
    }
    return true;
}


/**
 * @brief The function generates a new random version 4 uuid.
 *
 * @return The generated uuid.
 */
UUID tkbc_uuid_generate(void) {
    UUID uuid;
    tkbc_uuid_fill_random_bytes(uuid.bytes, sizeof(uuid.bytes));

    // Set the version field to version 4.
    uuid.bytes[6] = (unsigned char) ((uuid.bytes[6] & 0x0F) | 0x40);
    // Set the variant field to the RFC 4122 variant.
    uuid.bytes[8] = (unsigned char) ((uuid.bytes[8] & 0x3F) | 0x80);

    // If the random source could not fill the buffer then fall back to a
    // deterministic uuid that is derived from the nil uuid.
    if (tkbc_uuid_is_nil(uuid)) {
        uuid = tkbc_uuid_nil();
    }

    return uuid;
}


/**
 * @brief The function creates a deterministic uuid that is derived from the
 * given number. The raw binary representation of the number is stored in the
 * uuid. Like the uuids generated by tkbc_uuid_generate the version field is
 * set to version 4 and the variant field is set to the RFC 4122 variant.
 *
 * @param number The number that should be used as the basis for the uuid.
 * @return The generated uuid.
 */
UUID tkbc_uuid_from_number(size_t number) {
    UUID uuid = {0};

    // Store the raw bytes of the number in the last bytes of the uuid.
    for (size_t i = 0; i < sizeof(number); ++i) {
        uuid.bytes[sizeof(uuid.bytes) - i - 1] =
            (unsigned char) (number >> (i * 8));
    }

    // Set the version field to version 4.
    uuid.bytes[6] = (unsigned char) ((uuid.bytes[6] & 0x0F) | 0x40);
    // Set the variant field to the RFC 4122 variant.
    uuid.bytes[8] = (unsigned char) ((uuid.bytes[8] & 0x3F) | 0x80);

    return uuid;
}


/**
 * @brief The function converts a single nibble to its lowercase hexadecimal
 * character representation.
 *
 * @param value The nibble that should be converted. Only values in the range of
 * 0 to 15 are valid.
 * @return The lowercase hexadecimal character of the nibble.
 */
static char tkbc_uuid_nibble_to_hex(unsigned char value) {
    return value < 10 ? (char) ('0' + value) : (char) ('a' + (value - 10));
}

/**
 * @brief The function writes the canonical textual representation of the given
 * uuid into the given output buffer. The textual representation looks like
 * "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx" where each x is a hex digit.
 *
 * @param uuid The uuid that should be converted.
 * @param out A buffer of at least 37 bytes where the null terminated string
 * should be stored.
 */
void tkbc_uuid_to_string(UUID uuid, char out[37]) {
    size_t index = 0;
    for (size_t i = 0; i < 16; ++i) {
        if (i == 4 || i == 6 || i == 8 || i == 10) {
            out[index++] = '-';
        }
        out[index++] = tkbc_uuid_nibble_to_hex((unsigned char) (uuid.bytes[i] >> 4));
        out[index++] = tkbc_uuid_nibble_to_hex((unsigned char) (uuid.bytes[i] & 0x0F));
    }
    out[index] = '\0';
}

/**
 * @brief The function converts a single hexadecimal character to its numeric
 * value.
 *
 * @param digit The hexadecimal character that should be converted.
 * @return The numeric value of the hexadecimal character in the range of 0 to
 * 15, or -1 if the character is no hexadecimal character.
 */
static int tkbc_uuid_hex_to_value(char digit) {
    if (digit >= '0' && digit <= '9') {
        return digit - '0';
    }
    if (digit >= 'a' && digit <= 'f') {
        return digit - 'a' + 10;
    }
    if (digit >= 'A' && digit <= 'F') {
        return digit - 'A' + 10;
    }
    return -1;
}

/**
 * @brief The function parses the canonical textual representation of the given
 * uuid and stores the parsed uuid in the given uuid object.
 *
 * @param str The null terminated string that contains the uuid in its canonical
 * textual representation.
 * @param uuid The uuid object where the parsed uuid should be stored.
 * @return True if the string could be parsed successfully, otherwise false.
 */
bool tkbc_uuid_from_string(const char *str, UUID *uuid) {
    if (!str || !uuid) {
        return false;
    }

    UUID parsed = {0};
    size_t byte_index = 0;
    for (size_t i = 0; i < 36; ++i) {
        if (i == 8 || i == 13 || i == 18 || i == 23) {
            if (str[i] != '-') {
                return false;
            }
            continue;
        }

        int high = tkbc_uuid_hex_to_value(str[i]);
        int low = tkbc_uuid_hex_to_value(str[i + 1]);
        if (high < 0 || low < 0) {
            return false;
        }
        parsed.bytes[byte_index++] = (unsigned char) ((high << 4) | low);
        ++i;
    }

    if (str[36] != '\0' || byte_index != 16) {
        return false;
    }

    *uuid = parsed;
    return true;
}
