#ifndef TKBC_UUID_H_
#define TKBC_UUID_H_

#include <stdbool.h>
#include <stddef.h>

/**
 * @brief The structure represents a version 4 uuid (RFC 4122). It stores the
 * 128 bits of the uuid in its raw binary form.
 */
typedef struct {
    unsigned char bytes[16];  // The raw 128 bits of the uuid.
} UUID;

/**
 * @brief The function returns the nil uuid. The nil uuid is the uuid where all
 * bytes are zero. It is used to represent the state where no script is loaded.
 *
 * @return The nil uuid.
 */
UUID tkbc_uuid_nil(void);

/**
 * @brief The function checks if the given uuid is the nil uuid.
 *
 * @param uuid The uuid that should be checked.
 * @return True if all bytes of the uuid are zero, otherwise false.
 */
bool tkbc_uuid_is_nil(UUID uuid);

/**
 * @brief The function checks if the two given uuids are equal.
 *
 * @param a The first uuid that should be compared.
 * @param b The second uuid that should be compared.
 * @return True if the two uuids are byte wise equal, otherwise false.
 */
bool tkbc_uuid_equals(UUID a, UUID b);

/**
 * @brief The function generates a new random version 4 uuid.
 *
 * @return The generated uuid.
 */
UUID tkbc_uuid_generate(void);

/**
 * @brief The function creates a deterministic uuid that is derived from the
 * given number. The raw binary representation of the number is stored in the
 * uuid. Like the uuids generated by tkbc_uuid_generate the version field is
 * set to version 4 and the variant field is set to the RFC 4122 variant.
 *
 * @param number The number that should be used as the basis for the uuid.
 * @return The generated uuid.
 */
UUID tkbc_uuid_from_number(size_t number);

/**
 * @brief The function writes the canonical textual representation of the given
 * uuid into the given output buffer. The textual representation looks like
 * "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx" where each x is a hex digit.
 *
 * @param uuid The uuid that should be converted.
 * @param out A buffer of at least 37 bytes where the null terminated string
 * should be stored.
 */
void tkbc_uuid_to_string(UUID uuid, char out[37]);

/**
 * @brief The function parses the canonical textual representation of the given
 * uuid and stores the parsed uuid in the given uuid object.
 *
 * @param str The null terminated string that contains the uuid in its canonical
 * textual representation.
 * @param uuid The uuid object where the parsed uuid should be stored.
 * @return True if the string could be parsed successfully, otherwise false.
 */
bool tkbc_uuid_from_string(const char *str, UUID *uuid);

#endif  // TKBC_UUID_H_
